FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
COPY README.md ./
COPY app ./app
COPY consumers ./consumers
RUN uv sync --frozen --no-dev

CMD ["uv", "run", "--no-sync", "python", "-m", "consumers.meal_analysis.main"]
